@echo off


set /p location_IP=Infranet_properties_path:

:x

:: %userprofile%

if exist %userprofile%\node_modules\@walmartlabs echo Walmart exists
if not exist %userprofile%\node_modules\@walmartlabs CMD /C npm i @walmartlabs/json-to-simple-graphql-schema

pause

:: clear screen
cls

:: Get object name and file name
set /p arg1=Object name:
set /p arg2=Json file name (without extension):
set /p location=Location (project location must be defined in this format "C:\..\"):

echo Object name: %arg1%
echo Json file name: %arg2%.json
echo Project location: %location%

::Replace Infranet.properties
xcopy "%location_IP%\Infranet.properties" "%location%\src\main\resources\" /y
xcopy "%location_IP%\Infranet.properties" "%location%" /y
xcopy "%location_IP%\Infranet.properties" "%location%\target\classes" /y

jar uf .\J2Json.jar Infranet.properties
pwd
:: Json conversion
java -jar .\J2Json.jar %arg1% %arg2%


:: Graphql conversion
type %arg2%.json | npx json-to-simple-graphql-schema > %arg2%.graphqls


:: Append extra code
echo type Query{>>.\%arg2%.graphqls 
echo search(poid:String,object:String):[AutogeneratedMainType]>>.\%arg2%.graphqls
echo }>>.\%arg2%.graphqls


:: Place file in project directory
::del /s /q "%location%\*.graphqls"
del /s /q "%location%\target\classes\graphql\*.graphqls"
del /s /q "%location%\src\main\resources\graphql\*.graphqls"

xcopy   ".\%arg2%.graphqls" "%location%\src\main\resources\graphql"
xcopy    ".\%arg2%.graphqls" "%location%\target\classes\graphql"

:: Delete local files
del  "%location%\*.json"
del  "%location%\*.graphqls"


echo Schema created successfully



echo Do you want to generate another schema (Yes/No)?

set /p answer=answer:

if %answer%==Yes (goto x)
if %answer%==yes (goto x)
if %answer%==Y (goto x)
if %answer%==y (goto x) else exit